### ISSUE TITLE
Repo is pointing to the old source.codeaurora.org URL

### ISSUE THREAD

**Issue by IsaacJT** [nxp-auto-goldvip/gvip-manifests#1]
`repo sync` no longer works as per the "S32G Vehicle Integration Platform (GoldVIP) User Manual" document as the manifests point to the old source.codeaurora.org URL, which no longer exists.

**Comment by InvTaoMorgan** [comment]
May I ask whether you executed "repo init -b develop -m default.xml -u https://github.com/nxp-auto-goldvip/gvip-manifests" in a completely empty folder, and then proceeded to modify ".repo/manifests/alb.xml"?

Or did you do this in a folder that has already undergone "repo sync" and "bitbake"?

I ask because currently, I made the modification to ".repo/manifests/alb.xml" in a folder that has previously undergone "bitbake," followed by "repo sync." However, I encountered some issues with hooks. As a result, I have made the changes in "sources/meta-gvip/recipes-extended/pkcs11-hse/pkcs11-hse.bb" with "SRCREV = "${AUTOREV}", and this allows me to complete "bitbake", as following:

BRANCH ?= "${RELEASE_BASE}"
#URL ?= "git://source.codeaurora.org/external/autobsps32/pkcs11-hse;protocol=https"
URL ?= "git://github.com/nxp-auto-linux/pkcs11-hse;protocol=https"
SRC_URI = "${URL};branch=${BRANCH}"
SRCREV = "${AUTOREV}"

Could it be possible for you to provide the proper method of execution? Thank you.

**Comment by IsaacJT** [comment]
This has now been resolved by NXP
